server:
  port: 8211


spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/data
    username: root
    password: 7305

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8